config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'memorymath' => 'welcome#memorymath'
  get 'play2048clone' => 'welcome#play2048clone'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
  def memorymath
  end

  def play2048clone
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= favicon_link_tag 'icon1.png' %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Cabin+Condensed' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Maven+Pro' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Coming+Soon' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Nunito' rel='stylesheet' type='text/css'>
  <title>Hailey HanGyeol Ryu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <h1><%= link_to "Hailey HanGyeol Ryu", root_path %></h1>
    <nav role="navigation">
      <ul>

        <li>
          <div class="ch-item-icon">
          <%= link_to "https://www.linkedin.com/in/haileyryu", target: "_blank" do %>
            <i  style="position: absolute;" class="fa fa-linkedin fa-3x"></i>
          <% end %>
          </div>
        </li>
        <li>
          <div class="ch-item-icon">
          <%= link_to "https://github.com/haileyR", target: "_blank" do %>
            <i  style="position: absolute;" class="fa fa-github fa-3x"></i>
          <% end %>
          </div>
        </li>
        <li>
          <div class="ch-item-icon envelop">
          <%= link_to "https://github.com/haileyR", target: "_blank" do %>
          <%= mail_to "hangyeolryu@gmail.com" do %>
            <i style="position: absolute;" class="fa fa-envelope fa-3x"></i>
          <% end %>

          <% end %>
          </div>
        </li>
      </ul>
    </nav>




  </header>

<%= yield %>



</body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</html>

app/views/projects/index.html.erb
<div class="hs-wrapper">
  <%= image_tag("openpac1.png") %>
  <%= image_tag("openpac2.png") %>
  <%= image_tag("openpac3.png") %>
  <%= image_tag("openpac4.png") %>
  <%= image_tag("openpac5.png") %>
  <%= image_tag("openpac1.png") %>

  <div class="hs-overlay">
    <span>OpenPAC <strong>JAN 2015</strong></span>
  </div>

</div>

app/views/welcome/index.html.erb
<div id="introduction-container">
  <h2 id="introduction-header">Hello, my name is Hailey.</h2>
  <p id="introduction">
    I am a software developer with Front-end and Back-end experience and a degree in electrical engineering. I am passionate about building products and enjoy the accomplishment. Also, I am innovative and ambitious to learn new technologies in a fast pace environment and have infectious and inspiring work ethic with ability to adapt and collaborate in a team setting.
  </p><br>
  <h2 id="introduction-header">TECHNICAL SKILLS</h2>
  <p id="introduction">
    JavaScript (jQuery, AJAX), Ruby, HTML5, CSS3, Java, C++, SQL (ActiveRecord), JSON, PHP<br>
    Rails, Sinatra, Android, Laravel, Foundation, Matlab<br>
    JUnit, RSpec, Jasmine<br>
    TDD (Test Driven Development), BDD (Behaviour Driven Development), Agile Development, MVC (Model, view, controller), Pair Programming<br>
    PostgreSQL, MySQL, SQLite3<br><br>
  </p>
</div>
<div id="down-arrow" align="center"><%= image_tag("arrow.jpg") %></div>
<div id="projects-container">
<h2 align="center">Projects</h2>
  <div class="hs-wrapper">
    <%= image_tag("openpac1.png", alt: "image01") %>
    <%= image_tag("openpac2.png", alt: "image02") %>
    <%= image_tag("openpac3.png", alt: "image03") %>
    <%= image_tag("openpac4.png", alt: "image04") %>
    <%= image_tag("openpac5.png", alt: "image05") %>

    <div class="hs-overlay">
      <span><h4>openPAC</h4>Platform where users can easily find out which legislators support the issues they care about and easily make a donation to that cause. Each legislator's page shows his/her relative positions on issues based on quantitative data. Also, users can generate stances that express an opinion regarding which legislators support a given position. Build in 8 days and with 4 other members.<br>Built with Ruby on Rails, AJAX, jQuery, and Sunlight Foundation’s Congress API. </span>
    </div>
    <div class="hs-footer" align="center">
      <%= link_to "Visit openPAC", "http://openpac.io/", target: "_blank" %>
      <%= link_to "View Code", "https://github.com/haileyR/openPAC", target: "_blank" %>
    </div>

  </div>

  <div class="hs-wrapper">
    <%= image_tag("kyv1.png", alt: "image01") %>
    <%= image_tag("kyv2.png", alt: "image02") %>
    <%= image_tag("kyv3.png", alt: "image03") %>
    <%= image_tag("kyv4.png", alt: "image04") %>
    <%= image_tag("kyv5.png", alt: "image05") %>

    <div class="hs-overlay">
      <span><h4>Know Your Values</h4>Web application that allows users to ask their friends to endorse their values so that they can develop and pitch them as their strengths.<br> Built with Ruby on Rails, AJAX and jQuery. </span>
    </div>
    <div class="hs-footer" align="center">
      <%= link_to "Visit Know Your Values", "https://know-your-values.herokuapp.com", target: "_blank" %>
      <%= link_to "View Code", "https://github.com/haileyR/Know-Your-Values-on-Rails", target: "_blank" %>
    </div>

  </div>

  <div class="hs-wrapper">
    <%= image_tag("memerymath1.png", alt: "image01") %>
    <%= image_tag("memerymath1.png", alt: "image02") %>
    <%= image_tag("memerymath1.png", alt: "image03") %>
    <%= image_tag("memerymath1.png", alt: "image04") %>
    <%= image_tag("memerymath1.png", alt: "image05") %>

    <div class="hs-overlay">
      <span><h4>Memory Math</h4>Math memory game built with JavaScript (jQuery).</span>
    </div>
    <div class="hs-footer" align="center">
      <%= link_to "Play ", memorymath_path%>
      <%= link_to "View Code", "https://github.com/haileyR/hangyeolryu/tree/master/app/assets/javascripts/memorymath", target: "_blank" %>
    </div>

  </div>

  <div class="hs-wrapper">
    <%= image_tag("overflow1.png", alt: "image01") %>
    <%= image_tag("overflow2.png", alt: "image02") %>
    <%= image_tag("overflow3.png", alt: "image03") %>
    <%= image_tag("overflow4.png", alt: "image04") %>
    <%= image_tag("overflow5.png", alt: "image05") %>

    <div class="hs-overlay">
      <span><h4>Stack Overflow clone</h4>Web application that allows users to post and answer questions, upvote/downvote and comment on questions and answers. Build in 3 days and with 4 other members.<br> Built with Ruby on Rails, AJAX and jQuery. TDD </span>
    </div>
    <div class="hs-footer" align="center">
      <%= link_to "Visit Overflow ", "https://pdfmh-overflow.herokuapp.com", target: "_blank" %>
      <%= link_to "View Code", "https://github.com/haileyR/pdfmh-dbc-overflow", target: "_blank" %>
    </div>

  </div>

  <div class="hs-wrapper">

    <div class="hs-overlay">
      <span><h4>2048 Clone</h4>2048 Clone built with JavaScript.</span>
    </div>
    <div class="hs-footer" align="center">
      <%= link_to "Play ", play2048clone_path%>
      <%= link_to "View Code", "https://github.com/haileyR/hangyeolryu/tree/master/app/assets/javascripts/play2048clone", target: "_blank" %>
    </div>

  </div>
</div>

  <footer align="center">
    <div class="ch-item aboutme" style="background-image: url(<%= asset_path('myphoto.jpg') %>);">
      <div class="ch-info">
        <h3>Thank you for visiting.</h3>
        <p>by Hailey HanGyeol Ryu <!-- <a href="/">About me</a> --></p>
      </div>
    </div>
  </footer>

app/views/welcome/memorymath.html.erb
<div class='memorymath-container' role='main'>
  <h2>Memory Math (hard)</h2>
  <i class="fa fa-times fa-5x"></i>
  <i class="fa fa-check fa-5x"></i>
  <p>Start the game and click a number, an operation, and a number to make a given number.<br>+1 for a correct answer, -2 for viewing the hint.</p>
  <table align="center" id='board' style="float: left;">
    <tr id='row0'>
      <td class="cell" id='0'><span class="insideTd"></span></td>
      <td class="cell" id='1'><span class="insideTd"></span></td>
      <td class="cell" id='2'><span class="insideTd"></span></td>
      <td class="cell" id='3'><span class="insideTd"></span></td>
    </tr>
    <tr id='row1'>
      <td class="cell" id='4'><span class="insideTd"></span></td>
      <td class="cell" id='5'><span class="insideTd"></span></td>
      <td class="cell" id='6'><span class="insideTd"></span></td>
      <td class="cell" id='7'><span class="insideTd"></span></td>
    </tr>
    <tr id='row2'>
      <td class="cell" id='8'><span class="insideTd"></span></td>
      <td class="cell" id='9'><span class="insideTd"></span></td>
      <td class="cell" id='10'><span class="insideTd"></span></td>
      <td class="cell" id='11'><span class="insideTd"></span></td>
    </tr>
    <tr id='row3'>
      <td class="cell" id='12'><span class="insideTd"></span></td>
      <td class="cell" id='13'><span class="insideTd"></span></td>
      <td class="cell" id='14'><span class="insideTd"></span></td>
      <td class="cell" id='15'><span class="insideTd"></span></td>
    </tr>
  </table>

  <div style="width:300px; float: right;">
    <button id='newgame' type="submit">New Game</button>
    <button type='button' id='hint'>Hint</button>
    <h2 id="numberToMake">Number to Make:<br>
      <p id='question'></p>
      <p id='equation'></p>
    </h2>
    <h2 id='score'></h2>
  </div>
</div>

app/views/welcome/play2048clone.html.erb
<div class="2048-container">
  <h2 id='score' align="center">Have Fun!</h2>
  <div id="game-grid">
    <button id="start-2048">New Game</button>
    <div class="grid-row">
      <div class="block"><div class="number"></div></div>
      <div class="block"><div class="number"></div></div>
      <div class="block"><div class="number"></div></div>
      <div class="block"><div class="number"></div></div>
    </div>
    <div class="grid-row">
      <div class="block"><div class="number"></div></div>
      <div class="block"><div class="number"></div></div>
      <div class="block"><div class="number"></div></div>
      <div class="block"><div class="number"></div></div>
    </div>
    <div class="grid-row">
      <div class="block"><div class="number"></div></div>
      <div class="block"><div class="number"></div></div>
      <div class="block"><div class="number"></div></div>
      <div class="block"><div class="number"></div></div>
    </div>
    <div class="grid-row">
      <div class="block"><div class="number"></div></div>
      <div class="block"><div class="number"></div></div>
      <div class="block"><div class="number"></div></div>
      <div class="block"><div class="number"></div></div>
    </div>
  </div>
</div>